class DashboardPage {
    constructor() { this.institutionActive = null; this.institutions = []; this.allClasses = []; }
    async render() {
        const m = document.getElementById('main-content');
        m.innerHTML = `<div style="text-align:center;padding:3rem"><div class="spinner"></div><p style="color:var(--text-muted);margin-top:0.75rem">Chargement...</p></div>`;
        try { const ir = await apiGet('/classes/institutions'); this.institutions = ir.data || []; if (!this.institutionActive && this.institutions.length) this.institutionActive = this.institutions[0]; await this.afficher(m); }
        catch(e) { m.innerHTML = `<div style="text-align:center;padding:3rem"><i class="fas fa-exclamation-triangle" style="font-size:2.5rem;color:var(--text-muted)"></i><p style="color:var(--text-secondary);margin-top:0.5rem">${e.message}</p></div>`; }
    }
    async afficher(m) {
        if (!this.institutions.length) { m.innerHTML = `<div style="text-align:center;padding:4rem"><i class="fas fa-school" style="font-size:4rem;color:var(--text-muted);display:block;margin-bottom:1rem"></i><h3 style="font-weight:700;margin-bottom:0.5rem">Aucune institution disponible</h3><p style="color:var(--text-secondary);margin-bottom:1.5rem">Créez votre première institution pour commencer.</p><button class="btn btn-primary" onclick="dashboard.ouvrirModalCreerInstitution()"><i class="fas fa-plus"></i> Créer une institution</button></div>`; return; }
        const inst = this.institutionActive; if (!inst) { this.institutionActive = this.institutions[0]; return this.afficher(m); }
        const cr = await apiGet(`/classes/institution/${inst.id}`); this.allClasses = cr.data || [];
        const classesAffichees = inst.niveau === 'secondaire' ? this.regrouperSecondaire() : this.allClasses;
        const labels = { maternelle: 'Maternelle', primaire: 'Primaire', secondaire: 'Secondaire' }, icons = { maternelle: 'child', primaire: 'child-reaching', secondaire: 'user-graduate' };
        const te = this.allClasses.reduce((s,c) => s + (c.nb_eleves||0), 0);
        const searchRendu = await CL.render('forms/search-bar', { id: 'search-classes', placeholder: 'Rechercher une classe...', oninput: "dashboard.filtrerClasses();var c=document.getElementById('search-classes-clear');if(c)c.style.display=this.value?'':'none'", onclear: 'dashboard.filtrerClasses()' });
        m.innerHTML = `<div class="dashboard-page">
  <div class="niveau-switcher">${this.institutions.map(i => `<button class="btn btn-sm ${i.id===inst.id?'btn-primary':'btn-ghost'}" onclick="dashboard.switchInstitution(${i.id})"><i class="fas fa-${icons[i.niveau]}"></i> ${labels[i.niveau]}</button>`).join('')}</div>
  <div style="display:flex;justify-content:center;gap:0.5rem;margin-bottom:1rem;flex-wrap:wrap"><button class="btn btn-info" onclick="dashboard.scannerQR()"><i class="fas fa-qrcode"></i> Scanner QR</button><button class="btn btn-primary" onclick="router.navigate('pointage')"><i class="fas fa-qrcode"></i> Lancer le pointage</button><button class="btn btn-success" onclick="dashboard.ouvrirImportExcel()"><i class="fas fa-file-excel"></i> Importer Excel</button></div>
  <div style="display:flex;justify-content:center;margin-bottom:1.25rem"><div class="ui-card" style="width:220px;text-align:center"><div class="card-body" style="padding:1.5rem"><div style="font-size:0.8rem;font-weight:600;color:var(--text-secondary);text-transform:uppercase;letter-spacing:0.03em;margin-bottom:0.75rem">Nombre d'élèves inscrits</div><div class="card-icon-wrapper" style="background:var(--gradient-1);box-shadow:0 8px 24px var(--primary-glow);margin:0 auto 0.75rem;width:48px;height:48px"><i class="fas fa-user-graduate"></i></div><div style="font-size:2rem;font-weight:800">${te}</div></div></div></div>
  ${searchRendu}
  <div class="section-header"><h3><i class="fas fa-layer-group"></i> Classes</h3><span style="color:var(--text-muted);font-size:0.78rem">${classesAffichees.length} classe(s)</span></div>
  <div class="classes-grid" id="classes-grid">${classesAffichees.map(c => this.carteClasse(c, inst)).join('')}</div>
  <input type="file" id="import-file-dashboard" accept=".xlsx,.xls" style="display:none" onchange="dashboard.traiterImportGlobal()"></div>`;
    }
    regrouperSecondaire() { const groupes = {}, ordre = { '7ème':1, '8ème':2, '1ère':3, '2ème':4, '3ème':5, '4ème':6 }; for (const c of this.allClasses) { const cle = c.niveau_detail; if (!groupes[cle]) groupes[cle] = { ...c, options: [], nb_eleves: 0, presents: 0, taux: '0.0' }; groupes[cle].nb_eleves += c.nb_eleves || 0; groupes[cle].presents += c.presents || 0; if (c.option_id) groupes[cle].options.push(c); } for (const k of Object.keys(groupes)) { const g = groupes[k]; g.taux = g.nb_eleves > 0 ? ((g.presents / g.nb_eleves) * 100).toFixed(1) : '0.0'; } return Object.values(groupes).sort((a,b) => (ordre[a.niveau_detail]||99) - (ordre[b.niveau_detail]||99)); }
    carteClasse(c, inst) { const colors = { maternelle: 'linear-gradient(135deg,#f472b6,#ec4899)', primaire: 'linear-gradient(135deg,#38bdf8,#0ea5e9)', secondaire: 'linear-gradient(135deg,#818cf8,#6366f1)' }, shadows = { maternelle: 'rgba(244,114,182,0.35)', primaire: 'rgba(56,189,248,0.35)', secondaire: 'rgba(129,140,248,0.35)' }; const tauxColor = (c.taux||0) >= 70 ? 'var(--success)' : (c.taux||0) >= 40 ? 'var(--warning)' : 'var(--danger)'; const aDesOptions = c.options && c.options.length > 0; const nomAffichage = inst.niveau === 'secondaire' ? `${c.niveau_detail}${aDesOptions ? ' (options)' : ''}` : c.nom_classe; const onclick = aDesOptions ? `event.stopPropagation();dashboard.ouvrirModalOptions('${c.niveau_detail}','${inst.id}')` : `router.navigate('classe/${c.id}')`; return `<div class="ui-card card-hoverable classe-item" data-nom="${nomAffichage.toLowerCase()}" onclick="${onclick}"><div class="card-icon-wrapper" style="background:${colors[inst.niveau]};box-shadow:0 8px 24px ${shadows[inst.niveau]}"><i class="fas fa-users"></i></div><div class="card-body"><h4 style="font-weight:700;font-size:1rem;margin-bottom:0.5rem">${nomAffichage}</h4><div style="display:flex;gap:1rem;margin-top:0.5rem"><div style="text-align:center;flex:1"><div style="font-size:1.3rem;font-weight:700">${c.nb_eleves||0}</div><div style="color:var(--text-muted);font-size:0.68rem;text-transform:uppercase">Élèves</div></div><div style="text-align:center;flex:1"><div style="font-size:1.3rem;font-weight:700;color:var(--success)">${c.presents||0}</div><div style="color:var(--text-muted);font-size:0.68rem;text-transform:uppercase">Présents</div></div><div style="text-align:center;flex:1"><div style="font-size:1.3rem;font-weight:700;color:${tauxColor}">${c.taux||0}%</div><div style="color:var(--text-muted);font-size:0.68rem;text-transform:uppercase">Présence</div></div></div><div style="margin-top:0.75rem;background:var(--input-bg);border-radius:6px;height:5px;overflow:hidden"><div style="width:${c.taux||0}%;height:100%;background:${tauxColor};border-radius:6px;transition:width 0.8s cubic-bezier(0.4,0,0.2,1)"></div></div></div><div class="card-footer">${aDesOptions?`<span class="badge badge-info"><i class="fas fa-cog"></i> ${c.options.length} option(s)</span>`:'<span><i class="fas fa-arrow-right"></i> Ouvrir</span>'}</div></div>`; }
    filtrerClasses() { const q = document.getElementById('search-classes')?.value.toLowerCase() || ''; document.querySelectorAll('.classe-item').forEach(el => { el.style.display = el.dataset.nom.includes(q) ? '' : 'none'; }); }
    async ouvrirModalOptions(niveauDetail, institutionId) { const overlay = document.createElement('div'); overlay.className = 'modal-overlay'; overlay.id = 'modal-options'; overlay.onclick = e => { if (e.target === overlay) overlay.remove(); }; overlay.innerHTML = `<div style="text-align:center;padding:3rem"><div class="spinner"></div></div>`; document.body.appendChild(overlay); try { const res = await apiGet(`/classes/options/${institutionId}/${niveauDetail}`); const options = res.data || []; const icns = { CG:'chart-line', MG:'cogs', BC:'flask', MP:'calculator', PE:'book', EL:'bolt', CT:'cut' }; overlay.innerHTML = `<div class="modal modal-md" onclick="event.stopPropagation()"><div class="modal-header"><h3><i class="fas fa-cogs"></i> ${niveauDetail} - Choisir une option</h3><button class="modal-close" onclick="document.getElementById('modal-options').remove()"><i class="fas fa-times"></i></button></div><div class="modal-body" style="display:flex;flex-direction:column;gap:0.6rem">${options.length?options.map(o=>`<div class="ui-card card-hoverable" onclick="document.getElementById('modal-options').remove();router.navigate('classe/${o.id}')"><div style="display:flex;align-items:center;gap:0.8rem;padding:0.8rem 1rem"><div style="width:40px;height:40px;border-radius:10px;background:var(--gradient-1);display:flex;align-items:center;justify-content:center;color:white;font-size:1rem"><i class="fas fa-${icns[o.option_code]||'book'}"></i></div><div style="flex:1"><strong>${o.option_nom}</strong><p style="color:var(--text-muted);font-size:0.78rem">${o.option_code} · ${o.nb_eleves||0} élèves</p></div><i class="fas fa-chevron-right" style="color:var(--text-muted)"></i></div></div>`).join(''):'<p style="text-align:center;color:var(--text-muted);padding:1rem">Aucune option</p>'}</div><div class="modal-footer"><button class="btn btn-ghost btn-sm" onclick="document.getElementById('modal-options').remove()"><i class="fas fa-times"></i> Fermer</button></div></div>`; } catch(e) { overlay.innerHTML = `<div class="modal modal-md"><div class="modal-header"><h3>Erreur</h3></div><div class="modal-body"><p>${e.message}</p></div></div>`; } }
    async switchInstitution(id) { this.institutionActive = this.institutions.find(i => i.id === id); const labels = { maternelle: 'Maternelle', primaire: 'Primaire', secondaire: 'Secondaire' }, icons = { maternelle: 'child', primaire: 'child-reaching', secondaire: 'user-graduate' }; const nivEl = document.getElementById('header-institution-niveau'); const logoEl = document.getElementById('header-logo'); if (nivEl) nivEl.innerHTML = `<i class="fas fa-${icons[this.institutionActive.niveau]}"></i> ${labels[this.institutionActive.niveau]}`; if (logoEl) logoEl.src = this.institutionActive.logo || '/assets/logo-ecole.png'; await this.afficher(document.getElementById('main-content')); }

    // ==================== IMPORT EXCEL ====================
    ouvrirImportExcel() { const overlay = document.createElement('div'); overlay.className = 'modal-overlay'; overlay.id = 'modal-import-dashboard'; overlay.onclick = e => { if (e.target === overlay) overlay.remove(); }; overlay.innerHTML = `<div class="modal" style="max-width:420px;text-align:center" onclick="event.stopPropagation()"><div class="modal-header"><h3><i class="fas fa-file-excel"></i> Importation massive</h3><button class="modal-close" onclick="document.getElementById('modal-import-dashboard').remove()"><i class="fas fa-times"></i></button></div><div class="modal-body" style="padding:2rem"><p style="color:var(--text-secondary);margin-bottom:1rem">Sélectionnez un fichier Excel (.xlsx) contenant les élèves à importer.</p><p style="color:var(--text-muted);font-size:0.8rem;margin-bottom:1rem">Colonnes : Nom & Postnom, Prénom, Date de naissance, Genre, Adresse, Classe, Option</p><button class="btn btn-primary btn-full" onclick="document.getElementById('modal-import-dashboard').remove();document.getElementById('import-file-dashboard').click()"><i class="fas fa-upload"></i> Choisir un fichier</button></div></div>`; document.body.appendChild(overlay); }
    async traiterImportGlobal() {
        const file = document.getElementById('import-file-dashboard')?.files[0]; if (!file) return;
        try {
            const eleves = await importExcelService.lireFichier(file);
            if (!eleves.length) { alert('Aucun élève trouvé'); return; }
            await importExcelService.chargerContexte(this.institutionActive?.id || 1);

            // Vérifier les options inconnues
            const optionsInconnues = importExcelService.verifierOptionsInconnues();
            let listeFinale = eleves;
            if (optionsInconnues.length > 0) {
                const resultat = await this.demanderCreationOptions(optionsInconnues);
                if (resultat === 'cancel') return;
                listeFinale = importExcelService.filtrerSansOptionsInconnues(optionsInconnues);
            }

            const overlay2 = document.createElement('div'); overlay2.className = 'modal-overlay'; overlay2.id = 'modal-progression-global';
            overlay2.innerHTML = `<div class="modal" style="max-width:400px;text-align:center" onclick="event.stopPropagation()"><div class="modal-body" style="padding:2rem"><div class="spinner"></div><p style="margin-top:1rem">Importation... <span id="import-count-global">0</span> / ${listeFinale.length}</p></div></div>`; document.body.appendChild(overlay2);

            let success = 0, errors = 0, skipped = 0;
            const processNext = (i) => {
                if (i >= listeFinale.length) { overlay2.innerHTML = `<div class="modal" style="max-width:400px;text-align:center" onclick="event.stopPropagation()"><div class="modal-body" style="padding:2rem"><i class="fas fa-check-circle" style="font-size:3rem;color:var(--success);margin-bottom:0.5rem;display:block"></i><h3>Import terminé</h3><p style="color:var(--text-secondary)">${success} importés · ${skipped} ignorés${errors>0?` · ${errors} erreurs`:''}</p><button class="btn btn-primary" style="margin-top:1.25rem;width:100%" onclick="document.getElementById('modal-progression-global').remove();dashboard.render()"><i class="fas fa-check"></i> OK</button></div></div>`; return; }
                const el = listeFinale[i];
                const nomPostnom = String(el.nom || '').trim(), prenom = String(el.prenom || '').trim(), date_naissance = String(el['date de naissance'] || ''), genre = (String(el.genre || 'M').trim().toUpperCase().charAt(0) === 'F') ? 'F' : 'M', adresse = String(el.adresse || '').trim(), classe_nom = String(el.classe || '').trim(), option_nom = String(el.option || '').trim();
                if (importExcelService.estDoublon(nomPostnom, prenom)) { skipped++; document.getElementById('import-count-global').textContent = i + 1; requestAnimationFrame(() => processNext(i + 1)); return; }
                const classe_id = importExcelService.trouverClasseId(classe_nom, option_nom);
                if (!classe_id) { errors++; document.getElementById('import-count-global').textContent = i + 1; requestAnimationFrame(() => processNext(i + 1)); return; }
                API.createEleve({ nom: nomPostnom, prenom, date_naissance, genre, adresse, classe_id }).then(r => { if (r && r.success) success++; else errors++; }).catch(() => errors++).finally(() => { document.getElementById('import-count-global').textContent = i + 1; requestAnimationFrame(() => processNext(i + 1)); });
            };
            processNext(0);
        } catch (ex) { console.error(ex); alert('Erreur: ' + ex); }
    }

    demanderCreationOptions(optionsInconnues) {
        return new Promise((resolve) => {
            const overlay = document.createElement('div'); overlay.className = 'modal-overlay'; overlay.id = 'modal-options-inconnues';
            overlay.onclick = e => { if (e.target === overlay) { overlay.remove(); resolve('cancel'); } };
            const lignes = optionsInconnues.map(o => `<tr><td><strong>${o.nom}</strong></td><td>${o.niveau}</td><td>${o.count} élève(s)</td></tr>`).join('');
            overlay.innerHTML = `<div class="modal" style="max-width:550px" onclick="event.stopPropagation()"><div class="modal-header"><h3><i class="fas fa-exclamation-triangle" style="color:var(--warning)"></i> Options inconnues détectées</h3><button class="modal-close" onclick="document.getElementById('modal-options-inconnues').remove();resolve('cancel')"><i class="fas fa-times"></i></button></div>
    <div class="modal-body"><p style="color:var(--text-secondary);margin-bottom:1rem">Ces options n'existent pas encore :</p><div class="table-container"><table class="data-table"><thead><tr><th>Option</th><th>Niveau</th><th>Élèves</th></tr></thead><tbody>${lignes}</tbody></table></div><p style="color:var(--text-muted);margin-top:1rem">Voulez-vous créer ces options maintenant ?</p></div>
    <div class="modal-footer"><button class="btn btn-ghost" onclick="document.getElementById('modal-options-inconnues').remove();resolve('cancel')">Ignorer</button><button class="btn btn-primary" onclick="document.getElementById('modal-options-inconnues').remove();dashboard.creerOptionsManquantes(optionsInconnues).then(resolve)"><i class="fas fa-plus"></i> Créer les options</button></div></div>`;
            document.body.appendChild(overlay);
        });
    }

    async creerOptionsManquantes(optionsInconnues) {
        const instSecondaire = this.institutions.find(i => i.niveau === 'secondaire');
        if (!instSecondaire) { alert('Aucune institution secondaire'); return 'cancel'; }
        for (const opt of optionsInconnues) {
            try { await apiPost('/classes/option/secondaire', { code: opt.code, nom: opt.nom, institution_id: instSecondaire.id }); } catch (e) {}
        }
        alert('Options créées ! Relancez l\'import.');
        return 'created';
    }

    // ==================== SCANNER QR ====================
    scannerQR() { const overlay = document.createElement('div'); overlay.className = 'modal-overlay'; overlay.id = 'modal-qr'; overlay.onclick = e => { if (e.target === overlay) { this.stopScanner(); overlay.remove(); } }; overlay.innerHTML = `<div class="modal" style="max-width:500px" onclick="event.stopPropagation()"><div class="modal-header"><h3><i class="fas fa-qrcode"></i> Scanner un QR code</h3><button class="modal-close" onclick="dashboard.stopScanner();document.getElementById('modal-qr').remove()"><i class="fas fa-times"></i></button></div><div class="modal-body" style="text-align:center"><div id="qr-reader" style="width:100%;max-width:400px;margin:0 auto;border-radius:var(--radius);overflow:hidden"></div><div id="qr-result" style="display:none;margin-top:1rem;padding:1rem;background:var(--success-light);border-radius:var(--radius);color:var(--success)"><i class="fas fa-check-circle"></i> <span id="qr-result-text"></span></div><div style="margin-top:1rem;padding-top:1rem;border-top:1px solid var(--glass-border)"><p style="color:var(--text-muted);font-size:0.85rem;margin-bottom:0.5rem"><i class="fas fa-image"></i> Ou importez une image :</p><input type="file" id="qr-file-input" accept="image/*" style="display:none" onchange="dashboard.scannerFichierQR()"><button class="btn btn-sm btn-primary" onclick="document.getElementById('qr-file-input').click()"><i class="fas fa-upload"></i> Choisir une image</button></div></div></div>`; document.body.appendChild(overlay); this.qrScanner = new Html5Qrcode("qr-reader"); this.qrScanner.start({ facingMode: "environment" }, { fps: 10, qrbox: { width: 250, height: 250 } }, (decodedText) => { document.getElementById('qr-result').style.display = 'block'; document.getElementById('qr-result-text').textContent = 'QR détecté ! Redirection...'; setTimeout(() => { this.stopScanner(); document.getElementById('modal-qr')?.remove(); this.traiterQR(decodedText); }, 500); }, () => {}).catch(() => { document.getElementById('qr-reader').innerHTML = `<p style="color:var(--text-muted);padding:2rem"><i class="fas fa-camera-slash" style="font-size:2rem;display:block;margin-bottom:0.5rem"></i>Caméra non disponible</p>`; }); }
    stopScanner() { if (this.qrScanner) { try { this.qrScanner.stop().catch(()=>{}); } catch(e) {} this.qrScanner = null; } }
    scannerFichierQR() { const file = document.getElementById('qr-file-input')?.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = (e) => { const img = new Image(); img.onload = () => { const canvas = document.createElement('canvas'); canvas.width = img.width; canvas.height = img.height; const ctx = canvas.getContext('2d'); ctx.drawImage(img, 0, 0); const code = jsQR(ctx.getImageData(0,0,canvas.width,canvas.height).data, canvas.width, canvas.height); if (code) { this.stopScanner(); document.getElementById('modal-qr')?.remove(); this.traiterQR(code.data); } else alert('Aucun QR détecté.'); }; img.src = e.target.result; }; reader.readAsDataURL(file); }
    traiterQR(decodedText) { if (decodedText.includes('/#eleves/')) { const id = decodedText.split('/#eleves/')[1]; if (id) router.navigate('eleves/' + id); } else if (decodedText.includes('#eleves/')) { const id = decodedText.split('#eleves/')[1]; if (id) router.navigate('eleves/' + id); } else alert('QR code invalide'); }

    // ==================== CRÉER INSTITUTION ====================
    ouvrirModalCreerInstitution() { const overlay = document.createElement('div'); overlay.className = 'modal-overlay'; overlay.id = 'modal-creer-inst'; overlay.onclick = e => { if (e.target === overlay) overlay.remove(); }; overlay.innerHTML = `<div class="modal" style="max-width:450px" onclick="event.stopPropagation()"><div class="modal-header"><h3><i class="fas fa-school"></i> Créer une institution</h3><button class="modal-close" onclick="document.getElementById('modal-creer-inst').remove()"><i class="fas fa-times"></i></button></div><div class="modal-body"><form onsubmit="return false"><div class="input-group"><label class="input-label">Nom <span class="required">*</span></label><div class="input-wrapper"><i class="fas fa-school input-icon"></i><input type="text" class="form-input" id="creer-inst-nom" placeholder="Complexe Scolaire Avenir" required></div></div><div class="input-group"><label class="input-label">Niveau <span class="required">*</span></label><div class="select-wrapper"><select class="form-select" id="creer-inst-niveau" required><option value="">Sélectionner</option><option value="maternelle">Maternelle</option><option value="primaire">Primaire</option><option value="secondaire">Secondaire</option></select><i class="fas fa-chevron-down select-arrow"></i></div></div><p style="color:var(--text-muted);font-size:0.8rem"><i class="fas fa-info-circle"></i> Pour le secondaire, 7ème et 8ème E.B créés. Options dans le profil.</p></form></div><div class="modal-footer"><button class="btn btn-ghost" onclick="document.getElementById('modal-creer-inst').remove()">Annuler</button><button class="btn btn-primary" onclick="dashboard.creerInstitution()"><i class="fas fa-save"></i> Créer</button></div></div>`; document.body.appendChild(overlay); }
    async creerInstitution() { const nom = document.getElementById('creer-inst-nom')?.value?.trim(), niveau = document.getElementById('creer-inst-niveau')?.value; if (!nom || !niveau) { alert('Champs requis'); return; } try { const r = await apiPost('/classes/institution', { nom, niveau }); if (r.success) { document.getElementById('modal-creer-inst')?.remove(); const ir = await apiGet('/classes/institutions'); this.institutions = ir.data || []; this.institutionActive = this.institutions[0] || null; await this.afficher(document.getElementById('main-content')); } else alert(r.message); } catch(e) { alert('Erreur: ' + e.message); } }
}