const fs = require('fs');const path = require('path');
const LOGS_PATH = path.join(__dirname, '..', '..', 'database', 'logs.json');
const BACKUP_PATH = path.join(__dirname, '..', '..', 'database', 'backup.json');
function getLogs() { try { if (!fs.existsSync(LOGS_PATH)) return []; const data = fs.readFileSync(LOGS_PATH, 'utf-8').trim().split('\n').filter(l => l); return data.map(l => { try { return JSON.parse(l); } catch(e) { return null; } }).filter(l => l); } catch(e) { return []; } }
function saveLog(log) { try { const dir = path.dirname(LOGS_PATH); if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true }); nettoyerVieuxLogs(); fs.appendFileSync(LOGS_PATH, JSON.stringify(log) + '\n'); } catch(e) {} }
function nettoyerVieuxLogs() { try { if (!fs.existsSync(LOGS_PATH)) return; const sixMois = Date.now() - (180 * 24 * 60 * 60 * 1000); const lignes = fs.readFileSync(LOGS_PATH, 'utf-8').trim().split('\n').filter(l => l); const recents = []; const anciens = []; lignes.forEach(l => { try { const log = JSON.parse(l); if (new Date(log.date).getTime() > sixMois) recents.push(l); else anciens.push(JSON.stringify(log)); } catch(e) { recents.push(l); } }); if (anciens.length > 0) { let backup = []; if (fs.existsSync(BACKUP_PATH)) { try { backup = JSON.parse(fs.readFileSync(BACKUP_PATH, 'utf-8')); } catch(e) {} } backup.push(...anciens.map(l => JSON.parse(l))); fs.writeFileSync(BACKUP_PATH, JSON.stringify(backup)); } fs.writeFileSync(LOGS_PATH, recents.join('\n') + (recents.length ? '\n' : '')); } catch(e) {} }
function requestLogger(req, res, next) { const originalJson = res.json; res.json = function(data) { const statut = data && data.success !== false ? 'réussi' : 'échoué'; saveLog({ date: new Date().toISOString(), type: `${req.method} ${req.baseUrl}${req.path}`, requete: `${req.method} ${req.originalUrl}`, detail: null, statut }); return originalJson.call(this, data); }; next(); }
const TYPE_CATEGORIES = { connexion: ['POST /api/auth/login', 'POST /api/auth/register', 'GET /api/auth/verify'], enregistrement: ['INSERT INTO'], modification: ['UPDATE'], suppression: ['DELETE FROM', 'DELETE '], navigation: ['GET /api/classes', 'GET /api/eleves', 'GET /api/presences'], pointage: ['POST /api/presences'], importation: ['POST /api/classes/option'], SQL: [], autre: [] };
function getCategorie(type) { for (const [cat, patterns] of Object.entries(TYPE_CATEGORIES)) { if (cat === 'SQL' || cat === 'autre') continue; if (patterns.some(p => type.includes(p))) return cat; } return 'autre'; }
function getCouleurType(categorie) { const couleurs = { connexion: '#3b82f6', enregistrement: '#10b981', modification: '#f59e0b', suppression: '#ef4444', navigation: '#8b5cf6', pointage: '#06b6d4', importation: '#ec4899', SQL: '#6366f1', autre: '#94a3b8' }; return couleurs[categorie] || '#94a3b8'; }
function getLabelType(categorie) { const labels = { connexion: 'Connexion', enregistrement: 'Enregistrement', modification: 'Modification', suppression: 'Suppression', navigation: 'Navigation', pointage: 'Pointage', importation: 'Importation', SQL: 'SQL', autre: 'Autre' }; return labels[categorie] || categorie; }
module.exports = { requestLogger, getLogs, getCategorie, getCouleurType, getLabelType };