const pool = require('../config/database');
const QRCode = require('qrcode');

class Professeur {
    static async findAll() { const [r] = await pool.query('SELECT p.*, GROUP_CONCAT(t.classe_id) as classes_titulaires_ids FROM professeurs p LEFT JOIN titulaires t ON p.id=t.professeur_id GROUP BY p.id ORDER BY p.nom, p.prenom'); return r; }
    static async findById(id) { const [prof] = await pool.query('SELECT p.* FROM professeurs p WHERE p.id=?', [id]); if (!prof.length) return null; const [classes_titulaires] = await pool.query('SELECT t.*, c.nom_classe, c.niveau_detail, c.institution_id FROM titulaires t JOIN classes c ON t.classe_id=c.id WHERE t.professeur_id=?', [id]); const [presences] = await pool.query('SELECT date_presence, statut, methode_pointage, heure_arrivee FROM presences_professeurs WHERE professeur_id=? ORDER BY date_presence DESC LIMIT 30', [id]); const [preparations] = await pool.query('SELECT pr.*, m.intitule as matiere_nom FROM preparations pr LEFT JOIN matieres m ON pr.matiere_id=m.id WHERE pr.professeur_id=? ORDER BY pr.date_preparation DESC LIMIT 30', [id]); return { ...prof[0], classes_titulaires, presences, preparations }; }
    static async create({ nom, prenom, date_naissance, genre, adresse, telephone, email, charge_horaire, date_embauche }) { const conn = await pool.getConnection(); try { const matricule = 'PROF' + Date.now(); const [r] = await conn.query('INSERT INTO professeurs (matricule, nom, prenom, date_naissance, genre, adresse, telephone, email, charge_horaire, date_embauche, qr_code) VALUES (?,?,?,?,?,?,?,?,?,?,?)', [matricule, nom, prenom, date_naissance, genre, adresse || null, telephone || null, email || null, charge_horaire || null, date_embauche, '']); const profId = r.insertId; const qrData = `#professeurs/${profId}`; let qrCode = ''; try { qrCode = await QRCode.toDataURL(qrData); } catch(e) {} await conn.query('UPDATE professeurs SET qr_code=? WHERE id=?', [qrCode, profId]); return { id: profId, matricule, qr_code: qrCode }; } finally { conn.release(); } }
    static async update(id, { nom, prenom, date_naissance, genre, adresse, telephone, email, charge_horaire, statut }) { const fields = []; const values = []; if (nom !== undefined) { fields.push('nom=?'); values.push(nom); } if (prenom !== undefined) { fields.push('prenom=?'); values.push(prenom); } if (date_naissance !== undefined) { fields.push('date_naissance=?'); values.push(date_naissance); } if (genre !== undefined) { fields.push('genre=?'); values.push(genre); } if (adresse !== undefined) { fields.push('adresse=?'); values.push(adresse); } if (telephone !== undefined) { fields.push('telephone=?'); values.push(telephone); } if (email !== undefined) { fields.push('email=?'); values.push(email); } if (charge_horaire !== undefined) { fields.push('charge_horaire=?'); values.push(charge_horaire); } if (statut !== undefined) { fields.push('statut=?'); values.push(statut); } if (fields.length > 0) { values.push(id); await pool.query(`UPDATE professeurs SET ${fields.join(',')} WHERE id=?`, values); } }
    static async delete(id) { const [r] = await pool.query('DELETE FROM professeurs WHERE id=?', [id]); return r.affectedRows > 0; }
    static async pointer({ professeur_id, statut, methode_pointage, pointe_par }) { const today = new Date().toISOString().split('T')[0]; const now = new Date().toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' }); const [existing] = await pool.query('SELECT id, statut FROM presences_professeurs WHERE professeur_id=? AND date_presence=?', [professeur_id, today]); if (existing.length > 0) { if (existing[0].statut === 'present') return { success: false, message: 'Déjà pointé' }; await pool.query('UPDATE presences_professeurs SET statut=?, heure_arrivee=?, methode_pointage=?, pointe_par=? WHERE id=?', [statut, statut === 'present' ? now : null, methode_pointage || 'QR', pointe_par || null, existing[0].id]); } else { await pool.query('INSERT INTO presences_professeurs (professeur_id, date_presence, statut, heure_arrivee, methode_pointage, pointe_par) VALUES (?,?,?,?,?,?)', [professeur_id, today, statut, statut === 'present' ? now : null, methode_pointage || 'QR', pointe_par || null]); } return { success: true }; }
    static async getPresenceDuJour(professeur_id) { const today = new Date().toISOString().split('T')[0]; const [r] = await pool.query('SELECT * FROM presences_professeurs WHERE professeur_id=? AND date_presence=?', [professeur_id, today]); return r.length ? r[0] : null; }
}

module.exports = Professeur;